import React, { createContext, useContext, useState, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';

export type Language = 'de' | 'en' | 'fr' | 'es' | 'it' | 'pl' | 'nl' | 'pt';

export const SUPPORTED_LANGUAGES: { code: Language; nativeLabel: string }[] = [
  { code: 'de', nativeLabel: 'Deutsch' },
  { code: 'en', nativeLabel: 'English' },
  { code: 'fr', nativeLabel: 'Français' },
  { code: 'es', nativeLabel: 'Español' },
  { code: 'it', nativeLabel: 'Italiano' },
  { code: 'pl', nativeLabel: 'Polski' },
  { code: 'nl', nativeLabel: 'Nederlands' },
  { code: 'pt', nativeLabel: 'Português' },
];

// Languages with full translations across ALL screens (including ClimateScreen).
// Used for the picker AND for initial language resolution so users never end up
// in a language where some screens are not yet localized.
// Expand once ClimateScreen is localized for FR/ES/IT/PL/NL/PT (Issue #83 follow-up).
const FULLY_LOCALIZED: Language[] = ['de', 'en'];

export const PICKER_LANGUAGES = SUPPORTED_LANGUAGES.filter((l) => FULLY_LOCALIZED.includes(l.code));

type TranslationValue = string | string[];

interface Translations {
  [key: string]: TranslationValue;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => TranslationValue | string;
}

const translations: Record<Language, Translations> = {
  de: {
    // Navigation
    'nav.calendar': '📅',
    'nav.agenda': '📋',

    // Calendar Screen
    'calendar.title': 'Pflanzkalender',
    'calendar.addPlant': 'Neue Pflanze',
    'calendar.months.short': [
      'Jan',
      'Feb',
      'Mär',
      'Apr',
      'Mai',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Okt',
      'Nov',
      'Dez',
    ],

    // Agenda Screen
    'agenda.previous': 'Vorher',
    'agenda.current': 'Aktuell',
    'agenda.next': 'Demnächst',
    'agenda.noActivities': 'Keine Aktivitäten',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mär 1-15',
      'Mär 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'Mai 1-15',
      'Mai 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Aug 1-15',
      'Aug 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Okt 1-15',
      'Okt 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dez 1-15',
      'Dez 16-31',
    ],

    // Settings Screen
    'settings.title': 'Pflanzkalender',
    'settings.theme': '🌙 System / Dunkel',
    'settings.language': '🌐 Deutsch / English',
    'settings.export': '📤 Daten als JSON exportieren',
    'settings.support': '☕ Support me',
    'settings.feedback': '📧 Feedback',
    'settings.about': 'Über',
    'settings.version': 'Version 1.3.0',
    'settings.license': 'Lizenz',
    'settings.licenseDetails':
      'Open Source • MIT Lizenz\nKeine kommerzielle Nutzung ohne Genehmigung',
    'settings.settings': 'Einstellungen',
    'settings.appearance': 'ERSCHEINUNGSBILD',
    'settings.dark': 'Dunkel',
    'settings.system': 'System',
    'settings.languageSection': 'SPRACHE',
    'settings.exportSection': 'EXPORTIEREN',
    'settings.exportData': 'Als JSON exportieren',
    'settings.about2': 'ÜBER',
    'settings.versionLabel': 'Version',
    'settings.exportSuccess': 'Export erfolgreich!',
    'settings.successTitle': 'Erfolg',
    'settings.feedbackLink': 'Feedback senden',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Pflanzen verwalten',
    'plants.add': '➕ Neue Pflanze hinzufügen',
    'plants.empty': 'Noch keine Pflanzen vorhanden',
    'plants.activities': 'Aktivitäten',
    'plants.deleteTitle': 'Pflanze löschen',
    'plants.deleteMessage': 'wirklich löschen?',
    'plants.deleteConfirm': 'Löschen',
    'plants.deleteCancel': 'Abbrechen',
  },
  en: {
    // Navigation
    'nav.calendar': '📅',
    'nav.agenda': '📋',

    // Calendar Screen
    'calendar.title': 'Plant Calendar',
    'calendar.addPlant': 'New Plant',
    'calendar.months.short': [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],

    // Agenda Screen
    'agenda.previous': 'Previous',
    'agenda.current': 'Current',
    'agenda.next': 'Next',
    'agenda.noActivities': 'No activities',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'May 1-15',
      'May 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Aug 1-15',
      'Aug 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Oct 1-15',
      'Oct 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dec 1-15',
      'Dec 16-31',
    ],

    // Settings Screen
    'settings.title': 'Plant Calendar',
    'settings.theme': '🌙 System / Dark',
    'settings.language': '🌐 German / English',
    'settings.export': '📤 Export data as JSON',
    'settings.support': '☕ Support me',
    'settings.feedback': '📧 Feedback',
    'settings.about': 'About',
    'settings.version': 'Version 1.3.0',
    'settings.license': 'License',
    'settings.licenseDetails': 'Open Source • MIT License\nNo commercial use without permission',
    'settings.settings': 'Settings',
    'settings.appearance': 'APPEARANCE',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.languageSection': 'LANGUAGE',
    'settings.exportSection': 'EXPORT',
    'settings.exportData': 'Export as JSON',
    'settings.about2': 'ABOUT',
    'settings.versionLabel': 'Version',
    'settings.exportSuccess': 'Export successful!',
    'settings.successTitle': 'Success',
    'settings.feedbackLink': 'Send Feedback',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Manage Plants',
    'plants.add': '➕ Add New Plant',
    'plants.empty': 'No plants yet',
    'plants.activities': 'Activities',
    'plants.deleteTitle': 'Delete Plant',
    'plants.deleteMessage': 'really delete?',
    'plants.deleteConfirm': 'Delete',
    'plants.deleteCancel': 'Cancel',
  },
  fr: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendrier des plantes',
    'calendar.addPlant': 'Nouvelle plante',
    'calendar.months.short': [
      'Jan',
      'Fév',
      'Mar',
      'Avr',
      'Mai',
      'Juin',
      'Juil',
      'Août',
      'Sep',
      'Oct',
      'Nov',
      'Déc',
    ],
    'agenda.previous': 'Précédent',
    'agenda.current': 'Actuel',
    'agenda.next': 'Prochain',
    'agenda.noActivities': 'Aucune activité',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Fév 1-15',
      'Fév 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Avr 1-15',
      'Avr 16-30',
      'Mai 1-15',
      'Mai 16-31',
      'Juin 1-15',
      'Juin 16-30',
      'Juil 1-15',
      'Juil 16-31',
      'Août 1-15',
      'Août 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Oct 1-15',
      'Oct 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Déc 1-15',
      'Déc 16-31',
    ],
    'settings.settings': 'Paramètres',
    'settings.appearance': 'APPARENCE',
    'settings.dark': 'Sombre',
    'settings.system': 'Système',
    'settings.languageSection': 'LANGUE',
    'settings.exportSection': 'EXPORTER',
    'settings.exportData': 'Exporter en JSON',
    'settings.about2': 'À PROPOS',
    'settings.versionLabel': 'Version',
    'settings.exportSuccess': 'Exportation réussie !',
    'settings.successTitle': 'Succès',
    'settings.feedbackLink': 'Envoyer des commentaires',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gérer les plantes',
    'plants.add': '➕ Ajouter une plante',
    'plants.empty': 'Aucune plante pour le moment',
    'plants.activities': 'Activités',
    'plants.deleteTitle': 'Supprimer la plante',
    'plants.deleteMessage': 'vraiment supprimer ?',
    'plants.deleteConfirm': 'Supprimer',
    'plants.deleteCancel': 'Annuler',
  },
  es: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendario de plantas',
    'calendar.addPlant': 'Nueva planta',
    'calendar.months.short': [
      'Ene',
      'Feb',
      'Mar',
      'Abr',
      'May',
      'Jun',
      'Jul',
      'Ago',
      'Sep',
      'Oct',
      'Nov',
      'Dic',
    ],
    'agenda.previous': 'Anterior',
    'agenda.current': 'Actual',
    'agenda.next': 'Próximo',
    'agenda.noActivities': 'Sin actividades',
    'agenda.months': [
      'Ene 1-15',
      'Ene 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Abr 1-15',
      'Abr 16-30',
      'May 1-15',
      'May 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Ago 1-15',
      'Ago 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Oct 1-15',
      'Oct 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dic 1-15',
      'Dic 16-31',
    ],
    'settings.settings': 'Configuración',
    'settings.appearance': 'APARIENCIA',
    'settings.dark': 'Oscuro',
    'settings.system': 'Sistema',
    'settings.languageSection': 'IDIOMA',
    'settings.exportSection': 'EXPORTAR',
    'settings.exportData': 'Exportar como JSON',
    'settings.about2': 'ACERCA DE',
    'settings.versionLabel': 'Versión',
    'settings.exportSuccess': '¡Exportación exitosa!',
    'settings.successTitle': 'Éxito',
    'settings.feedbackLink': 'Enviar comentarios',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gestionar plantas',
    'plants.add': '➕ Añadir nueva planta',
    'plants.empty': 'Aún no hay plantas',
    'plants.activities': 'Actividades',
    'plants.deleteTitle': 'Eliminar planta',
    'plants.deleteMessage': '¿realmente eliminar?',
    'plants.deleteConfirm': 'Eliminar',
    'plants.deleteCancel': 'Cancelar',
  },
  it: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendario delle piante',
    'calendar.addPlant': 'Nuova pianta',
    'calendar.months.short': [
      'Gen',
      'Feb',
      'Mar',
      'Apr',
      'Mag',
      'Giu',
      'Lug',
      'Ago',
      'Set',
      'Ott',
      'Nov',
      'Dic',
    ],
    'agenda.previous': 'Precedente',
    'agenda.current': 'Attuale',
    'agenda.next': 'Prossimo',
    'agenda.noActivities': 'Nessuna attività',
    'agenda.months': [
      'Gen 1-15',
      'Gen 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'Mag 1-15',
      'Mag 16-31',
      'Giu 1-15',
      'Giu 16-30',
      'Lug 1-15',
      'Lug 16-31',
      'Ago 1-15',
      'Ago 16-31',
      'Set 1-15',
      'Set 16-30',
      'Ott 1-15',
      'Ott 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dic 1-15',
      'Dic 16-31',
    ],
    'settings.settings': 'Impostazioni',
    'settings.appearance': 'ASPETTO',
    'settings.dark': 'Scuro',
    'settings.system': 'Sistema',
    'settings.languageSection': 'LINGUA',
    'settings.exportSection': 'ESPORTA',
    'settings.exportData': 'Esporta come JSON',
    'settings.about2': 'INFORMAZIONI',
    'settings.versionLabel': 'Versione',
    'settings.exportSuccess': 'Esportazione riuscita!',
    'settings.successTitle': 'Successo',
    'settings.feedbackLink': 'Invia feedback',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gestisci le piante',
    'plants.add': '➕ Aggiungi nuova pianta',
    'plants.empty': 'Nessuna pianta ancora',
    'plants.activities': 'Attività',
    'plants.deleteTitle': 'Elimina pianta',
    'plants.deleteMessage': 'eliminare davvero?',
    'plants.deleteConfirm': 'Elimina',
    'plants.deleteCancel': 'Annulla',
  },
  pl: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Kalendarz roślin',
    'calendar.addPlant': 'Nowa roślina',
    'calendar.months.short': [
      'Sty',
      'Lut',
      'Mar',
      'Kwi',
      'Maj',
      'Cze',
      'Lip',
      'Sie',
      'Wrz',
      'Paź',
      'Lis',
      'Gru',
    ],
    'agenda.previous': 'Poprzedni',
    'agenda.current': 'Bieżący',
    'agenda.next': 'Następny',
    'agenda.noActivities': 'Brak aktywności',
    'agenda.months': [
      'Sty 1-15',
      'Sty 16-31',
      'Lut 1-15',
      'Lut 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Kwi 1-15',
      'Kwi 16-30',
      'Maj 1-15',
      'Maj 16-31',
      'Cze 1-15',
      'Cze 16-30',
      'Lip 1-15',
      'Lip 16-31',
      'Sie 1-15',
      'Sie 16-31',
      'Wrz 1-15',
      'Wrz 16-30',
      'Paź 1-15',
      'Paź 16-31',
      'Lis 1-15',
      'Lis 16-30',
      'Gru 1-15',
      'Gru 16-31',
    ],
    'settings.settings': 'Ustawienia',
    'settings.appearance': 'WYGLĄD',
    'settings.dark': 'Ciemny',
    'settings.system': 'System',
    'settings.languageSection': 'JĘZYK',
    'settings.exportSection': 'EKSPORT',
    'settings.exportData': 'Eksportuj jako JSON',
    'settings.about2': 'O APLIKACJI',
    'settings.versionLabel': 'Wersja',
    'settings.exportSuccess': 'Eksport zakończony sukcesem!',
    'settings.successTitle': 'Sukces',
    'settings.feedbackLink': 'Wyślij opinię',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Zarządzaj roślinami',
    'plants.add': '➕ Dodaj nową roślinę',
    'plants.empty': 'Brak roślin',
    'plants.activities': 'Aktywności',
    'plants.deleteTitle': 'Usuń roślinę',
    'plants.deleteMessage': 'na pewno usunąć?',
    'plants.deleteConfirm': 'Usuń',
    'plants.deleteCancel': 'Anuluj',
  },
  nl: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Plantenkalender',
    'calendar.addPlant': 'Nieuwe plant',
    'calendar.months.short': [
      'Jan',
      'Feb',
      'Mrt',
      'Apr',
      'Mei',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Okt',
      'Nov',
      'Dec',
    ],
    'agenda.previous': 'Vorige',
    'agenda.current': 'Huidig',
    'agenda.next': 'Volgend',
    'agenda.noActivities': 'Geen activiteiten',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mrt 1-15',
      'Mrt 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'Mei 1-15',
      'Mei 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Aug 1-15',
      'Aug 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Okt 1-15',
      'Okt 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dec 1-15',
      'Dec 16-31',
    ],
    'settings.settings': 'Instellingen',
    'settings.appearance': 'UITERLIJK',
    'settings.dark': 'Donker',
    'settings.system': 'Systeem',
    'settings.languageSection': 'TAAL',
    'settings.exportSection': 'EXPORTEREN',
    'settings.exportData': 'Exporteren als JSON',
    'settings.about2': 'OVER',
    'settings.versionLabel': 'Versie',
    'settings.exportSuccess': 'Export geslaagd!',
    'settings.successTitle': 'Gelukt',
    'settings.feedbackLink': 'Feedback sturen',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Planten beheren',
    'plants.add': '➕ Nieuwe plant toevoegen',
    'plants.empty': 'Nog geen planten',
    'plants.activities': 'Activiteiten',
    'plants.deleteTitle': 'Plant verwijderen',
    'plants.deleteMessage': 'echt verwijderen?',
    'plants.deleteConfirm': 'Verwijderen',
    'plants.deleteCancel': 'Annuleren',
  },
  pt: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendário de plantas',
    'calendar.addPlant': 'Nova planta',
    'calendar.months.short': [
      'Jan',
      'Fev',
      'Mar',
      'Abr',
      'Mai',
      'Jun',
      'Jul',
      'Ago',
      'Set',
      'Out',
      'Nov',
      'Dez',
    ],
    'agenda.previous': 'Anterior',
    'agenda.current': 'Atual',
    'agenda.next': 'Próximo',
    'agenda.noActivities': 'Sem atividades',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Fev 1-15',
      'Fev 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Abr 1-15',
      'Abr 16-30',
      'Mai 1-15',
      'Mai 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Ago 1-15',
      'Ago 16-31',
      'Set 1-15',
      'Set 16-30',
      'Out 1-15',
      'Out 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dez 1-15',
      'Dez 16-31',
    ],
    'settings.settings': 'Configurações',
    'settings.appearance': 'APARÊNCIA',
    'settings.dark': 'Escuro',
    'settings.system': 'Sistema',
    'settings.languageSection': 'IDIOMA',
    'settings.exportSection': 'EXPORTAR',
    'settings.exportData': 'Exportar como JSON',
    'settings.about2': 'SOBRE',
    'settings.versionLabel': 'Versão',
    'settings.exportSuccess': 'Exportação bem-sucedida!',
    'settings.successTitle': 'Sucesso',
    'settings.feedbackLink': 'Enviar feedback',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gerir plantas',
    'plants.add': '➕ Adicionar nova planta',
    'plants.empty': 'Ainda sem plantas',
    'plants.activities': 'Atividades',
    'plants.deleteTitle': 'Eliminar planta',
    'plants.deleteMessage': 'eliminar mesmo?',
    'plants.deleteConfirm': 'Eliminar',
    'plants.deleteCancel': 'Cancelar',
  },
};

function detectSystemLanguage(): Language {
  try {
    let locale: string | undefined;
    if (Platform.OS === 'web') {
      // platform-safe: navigator only available in web context
      locale = typeof navigator !== 'undefined' ? navigator.language : undefined;
    }
    if (!locale) return 'de';
    const code = locale.split('-')[0].toLowerCase() as Language;
    return FULLY_LOCALIZED.includes(code) ? code : 'de';
  } catch {
    return 'de';
  }
}

const STORAGE_KEY = 'language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('de');
  const isUserSetRef = React.useRef(false);

  const setLanguage = async (lang: Language) => {
    isUserSetRef.current = true;
    setLanguageState(lang);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, lang);
    } catch (error) {
      console.error('Failed to save language:', error);
    }
  };

  const t = (key: string): TranslationValue | string => {
    return translations[language][key] || key;
  };

  // Load language from storage on mount; skip if user already chose a language
  React.useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((storedLang) => {
      if (isUserSetRef.current) return;
      if (storedLang && FULLY_LOCALIZED.includes(storedLang as Language)) {
        setLanguageState(storedLang as Language);
      } else {
        setLanguageState(detectSystemLanguage());
      }
    });
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
