import React, { createContext, useContext, useState, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';

export type Language = 'de' | 'en' | 'fr' | 'es' | 'it' | 'pl' | 'nl' | 'pt';

export const SUPPORTED_LANGUAGES: { code: Language; nativeLabel: string }[] = [
  { code: 'de', nativeLabel: 'Deutsch' },
  { code: 'en', nativeLabel: 'English' },
  { code: 'fr', nativeLabel: 'Français' },
  { code: 'es', nativeLabel: 'Español' },
  { code: 'it', nativeLabel: 'Italiano' },
  { code: 'pl', nativeLabel: 'Polski' },
  { code: 'nl', nativeLabel: 'Nederlands' },
  { code: 'pt', nativeLabel: 'Português' },
];

// Languages with full translations across ALL screens (including ClimateScreen).
// Used for the picker AND for initial language resolution so users never end up
// in a language where some screens are not yet localized.
// Expand once ClimateScreen is localized for FR/ES/IT/PL/NL/PT (Issue #83 follow-up).
const FULLY_LOCALIZED: Language[] = ['de', 'en'];

export const PICKER_LANGUAGES = SUPPORTED_LANGUAGES.filter((l) => FULLY_LOCALIZED.includes(l.code));

type TranslationValue = string | string[];

interface Translations {
  [key: string]: TranslationValue;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => TranslationValue | string;
}

const translations: Record<Language, Translations> = {
  de: {
    // Navigation
    'nav.calendar': '📅',
    'nav.agenda': '📋',

    // Calendar Screen
    'calendar.title': 'Pflanzkalender',
    'calendar.addPlant': 'Neue Pflanze',
    'calendar.months.short': [
      'Jan',
      'Feb',
      'Mär',
      'Apr',
      'Mai',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Okt',
      'Nov',
      'Dez',
    ],

    // Agenda Screen
    'agenda.previous': 'Vorher',
    'agenda.current': 'Aktuell',
    'agenda.next': 'Demnächst',
    'agenda.noActivities': 'Keine Aktivitäten',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mär 1-15',
      'Mär 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'Mai 1-15',
      'Mai 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Aug 1-15',
      'Aug 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Okt 1-15',
      'Okt 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dez 1-15',
      'Dez 16-31',
    ],

    // Settings Screen
    'settings.title': 'Pflanzkalender',
    'settings.theme': '🌙 System / Dunkel',
    'settings.language': '🌐 Deutsch / English',
    'settings.export': '📤 Daten als JSON exportieren',
    'settings.support': '☕ Support me',
    'settings.feedback': '📧 Feedback',
    'settings.about': 'Über',
    'settings.version': 'Version 1.3.0',
    'settings.license': 'Lizenz',
    'settings.licenseDetails':
      'Open Source • MIT Lizenz\nKeine kommerzielle Nutzung ohne Genehmigung',
    'settings.settings': 'Einstellungen',
    'settings.appearance': 'ERSCHEINUNGSBILD',
    'settings.dark': 'Dunkel',
    'settings.system': 'System',
    'settings.languageSection': 'SPRACHE',
    'settings.exportSection': 'EXPORTIEREN',
    'settings.exportData': 'Als JSON exportieren',
    'settings.about2': 'ÜBER',
    'settings.versionLabel': 'Version',
    'settings.exportSuccess': 'Export erfolgreich!',
    'settings.successTitle': 'Erfolg',
    'settings.feedbackLink': 'Feedback senden',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Pflanzen verwalten',
    'plants.add': '➕ Neue Pflanze hinzufügen',
    'plants.empty': 'Noch keine Pflanzen vorhanden',
    'plants.activities': 'Aktivitäten',
    'plants.deleteTitle': 'Pflanze löschen',
    'plants.deleteMessage': 'wirklich löschen?',
    'plants.deleteConfirm': 'Löschen',
    'plants.deleteCancel': 'Abbrechen',
    'plants.editTitle': 'Pflanze bearbeiten',
    'plants.editSave': 'Speichern',
    'plants.fieldName': 'Pflanzenname',
    'plants.fieldNotes': 'Notizen',
    'plants.fieldLocation': 'Standort',
    'plants.fieldCategory': 'Kategorie',
    'plants.addTitle': 'Neue Pflanze hinzufügen',
    'plants.fieldNamePlaceholder': 'z.B. Tomaten',
    'plants.fieldNotesPlaceholder': 'z.B. Beliebtes Gemüse für Balkon',
    'plants.addHint': 'Nach dem Hinzufügen kannst du Aktivitäten für die Pflanze erstellen.',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.add': 'Hinzufügen',
    'activity.add.title': 'Aktivität hinzufügen',
    'activity.add.subtitle': 'für',
    'activity.add.typeLabel': 'Aktivitätstyp *',
    'activity.add.periodLabel': 'Zeitraum *',
    'activity.add.from': 'Von',
    'activity.add.to': 'Bis',
    'activity.add.customLabel': 'Eigene Bezeichnung (optional)',
    'activity.edit.title': 'Aktivität bearbeiten',
    'activity.edit.nameLabel': 'Bezeichnung',
    'activity.edit.periodLabel': 'Zeitraum *',
    'activity.edit.deleteTitle': 'Aktivität löschen',
    'activity.edit.deleteMessage': 'Aktivität wirklich löschen?',
    'activity.edit.rangeError': 'Startmonat darf nicht nach dem Endmonat liegen.',
    'activity.edit.namePlaceholder': 'z.B. Aussäen',
    'activity.type.sow': 'Aussäen',
    'activity.type.plant': 'Pflanzen',
    'activity.type.fertilize': 'Düngen',
    'activity.type.water': 'Gießen',
    'activity.type.prune': 'Zurückschneiden',
    'activity.type.harvest': 'Ernten',
    'activity.type.protect': 'Winterschutz',
    'activity.type.mulch': 'Mulchen',
  },
  en: {
    // Navigation
    'nav.calendar': '📅',
    'nav.agenda': '📋',

    // Calendar Screen
    'calendar.title': 'Plant Calendar',
    'calendar.addPlant': 'New Plant',
    'calendar.months.short': [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],

    // Agenda Screen
    'agenda.previous': 'Previous',
    'agenda.current': 'Current',
    'agenda.next': 'Next',
    'agenda.noActivities': 'No activities',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'May 1-15',
      'May 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Aug 1-15',
      'Aug 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Oct 1-15',
      'Oct 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dec 1-15',
      'Dec 16-31',
    ],

    // Settings Screen
    'settings.title': 'Plant Calendar',
    'settings.theme': '🌙 System / Dark',
    'settings.language': '🌐 German / English',
    'settings.export': '📤 Export data as JSON',
    'settings.support': '☕ Support me',
    'settings.feedback': '📧 Feedback',
    'settings.about': 'About',
    'settings.version': 'Version 1.3.0',
    'settings.license': 'License',
    'settings.licenseDetails': 'Open Source • MIT License\nNo commercial use without permission',
    'settings.settings': 'Settings',
    'settings.appearance': 'APPEARANCE',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.languageSection': 'LANGUAGE',
    'settings.exportSection': 'EXPORT',
    'settings.exportData': 'Export as JSON',
    'settings.about2': 'ABOUT',
    'settings.versionLabel': 'Version',
    'settings.exportSuccess': 'Export successful!',
    'settings.successTitle': 'Success',
    'settings.feedbackLink': 'Send Feedback',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Manage Plants',
    'plants.add': '➕ Add New Plant',
    'plants.empty': 'No plants yet',
    'plants.activities': 'Activities',
    'plants.deleteTitle': 'Delete Plant',
    'plants.deleteMessage': 'really delete?',
    'plants.deleteConfirm': 'Delete',
    'plants.deleteCancel': 'Cancel',
    'plants.editTitle': 'Edit Plant',
    'plants.editSave': 'Save',
    'plants.fieldName': 'Plant name',
    'plants.fieldNotes': 'Notes',
    'plants.fieldLocation': 'Location',
    'plants.fieldCategory': 'Category',
    'plants.addTitle': 'Add New Plant',
    'plants.fieldNamePlaceholder': 'e.g. Tomatoes',
    'plants.fieldNotesPlaceholder': 'e.g. Popular vegetable for balcony',
    'plants.addHint': 'After adding, you can create activities for the plant.',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.add': 'Add',
    'activity.add.title': 'Add Activity',
    'activity.add.subtitle': 'for',
    'activity.add.typeLabel': 'Activity type *',
    'activity.add.periodLabel': 'Period *',
    'activity.add.from': 'From',
    'activity.add.to': 'To',
    'activity.add.customLabel': 'Custom label (optional)',
    'activity.edit.title': 'Edit Activity',
    'activity.edit.nameLabel': 'Label',
    'activity.edit.periodLabel': 'Period *',
    'activity.edit.deleteTitle': 'Delete Activity',
    'activity.edit.deleteMessage': 'Really delete this activity?',
    'activity.edit.rangeError': 'Start month must not be after end month.',
    'activity.edit.namePlaceholder': 'e.g. Sow',
    'activity.type.sow': 'Sow',
    'activity.type.plant': 'Plant',
    'activity.type.fertilize': 'Fertilize',
    'activity.type.water': 'Water',
    'activity.type.prune': 'Prune',
    'activity.type.harvest': 'Harvest',
    'activity.type.protect': 'Winter protection',
    'activity.type.mulch': 'Mulch',
  },
  fr: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendrier des plantes',
    'calendar.addPlant': 'Nouvelle plante',
    'calendar.months.short': [
      'Jan',
      'Fév',
      'Mar',
      'Avr',
      'Mai',
      'Juin',
      'Juil',
      'Août',
      'Sep',
      'Oct',
      'Nov',
      'Déc',
    ],
    'agenda.previous': 'Précédent',
    'agenda.current': 'Actuel',
    'agenda.next': 'Prochain',
    'agenda.noActivities': 'Aucune activité',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Fév 1-15',
      'Fév 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Avr 1-15',
      'Avr 16-30',
      'Mai 1-15',
      'Mai 16-31',
      'Juin 1-15',
      'Juin 16-30',
      'Juil 1-15',
      'Juil 16-31',
      'Août 1-15',
      'Août 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Oct 1-15',
      'Oct 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Déc 1-15',
      'Déc 16-31',
    ],
    'settings.settings': 'Paramètres',
    'settings.appearance': 'APPARENCE',
    'settings.dark': 'Sombre',
    'settings.system': 'Système',
    'settings.languageSection': 'LANGUE',
    'settings.exportSection': 'EXPORTER',
    'settings.exportData': 'Exporter en JSON',
    'settings.about2': 'À PROPOS',
    'settings.versionLabel': 'Version',
    'settings.exportSuccess': 'Exportation réussie !',
    'settings.successTitle': 'Succès',
    'settings.feedbackLink': 'Envoyer des commentaires',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gérer les plantes',
    'plants.add': '➕ Ajouter une plante',
    'plants.empty': 'Aucune plante pour le moment',
    'plants.activities': 'Activités',
    'plants.deleteTitle': 'Supprimer la plante',
    'plants.deleteMessage': 'vraiment supprimer ?',
    'plants.deleteConfirm': 'Supprimer',
    'plants.deleteCancel': 'Annuler',
    'plants.editTitle': 'Modifier la plante',
    'plants.editSave': 'Enregistrer',
    'plants.fieldName': 'Nom de la plante',
    'plants.fieldNotes': 'Notes',
    'plants.fieldLocation': 'Emplacement',
    'plants.fieldCategory': 'Catégorie',
    'plants.addTitle': 'Ajouter une plante',
    'plants.fieldNamePlaceholder': 'ex. Tomates',
    'plants.fieldNotesPlaceholder': 'ex. Légume populaire pour balcon',
    'plants.addHint': "Après l'ajout, vous pouvez créer des activités pour la plante.",
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.add': 'Ajouter',
    'activity.add.title': 'Ajouter une activité',
    'activity.add.subtitle': 'pour',
    'activity.add.typeLabel': "Type d'activité *",
    'activity.add.periodLabel': 'Période *',
    'activity.add.from': 'De',
    'activity.add.to': 'À',
    'activity.add.customLabel': 'Libellé personnalisé (optionnel)',
    'activity.edit.title': "Modifier l'activité",
    'activity.edit.nameLabel': 'Libellé',
    'activity.edit.periodLabel': 'Période *',
    'activity.edit.deleteTitle': "Supprimer l'activité",
    'activity.edit.deleteMessage': 'Vraiment supprimer cette activité ?',
    'activity.edit.rangeError': 'Le mois de début ne peut pas être après le mois de fin.',
    'activity.edit.namePlaceholder': 'ex. Semer',
    'activity.type.sow': 'Semer',
    'activity.type.plant': 'Planter',
    'activity.type.fertilize': 'Fertiliser',
    'activity.type.water': 'Arroser',
    'activity.type.prune': 'Tailler',
    'activity.type.harvest': 'Récolter',
    'activity.type.protect': 'Protection hivernale',
    'activity.type.mulch': 'Pailler',
  },
  es: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendario de plantas',
    'calendar.addPlant': 'Nueva planta',
    'calendar.months.short': [
      'Ene',
      'Feb',
      'Mar',
      'Abr',
      'May',
      'Jun',
      'Jul',
      'Ago',
      'Sep',
      'Oct',
      'Nov',
      'Dic',
    ],
    'agenda.previous': 'Anterior',
    'agenda.current': 'Actual',
    'agenda.next': 'Próximo',
    'agenda.noActivities': 'Sin actividades',
    'agenda.months': [
      'Ene 1-15',
      'Ene 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Abr 1-15',
      'Abr 16-30',
      'May 1-15',
      'May 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Ago 1-15',
      'Ago 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Oct 1-15',
      'Oct 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dic 1-15',
      'Dic 16-31',
    ],
    'settings.settings': 'Configuración',
    'settings.appearance': 'APARIENCIA',
    'settings.dark': 'Oscuro',
    'settings.system': 'Sistema',
    'settings.languageSection': 'IDIOMA',
    'settings.exportSection': 'EXPORTAR',
    'settings.exportData': 'Exportar como JSON',
    'settings.about2': 'ACERCA DE',
    'settings.versionLabel': 'Versión',
    'settings.exportSuccess': '¡Exportación exitosa!',
    'settings.successTitle': 'Éxito',
    'settings.feedbackLink': 'Enviar comentarios',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gestionar plantas',
    'plants.add': '➕ Añadir nueva planta',
    'plants.empty': 'Aún no hay plantas',
    'plants.activities': 'Actividades',
    'plants.deleteTitle': 'Eliminar planta',
    'plants.deleteMessage': '¿realmente eliminar?',
    'plants.deleteConfirm': 'Eliminar',
    'plants.deleteCancel': 'Cancelar',
    'plants.editTitle': 'Editar planta',
    'plants.editSave': 'Guardar',
    'plants.fieldName': 'Nombre de la planta',
    'plants.fieldNotes': 'Notas',
    'plants.fieldLocation': 'Ubicación',
    'plants.fieldCategory': 'Categoría',
    'plants.addTitle': 'Agregar nueva planta',
    'plants.fieldNamePlaceholder': 'p.ej. Tomates',
    'plants.fieldNotesPlaceholder': 'p.ej. Vegetal popular para balcón',
    'plants.addHint': 'Después de agregar, puedes crear actividades para la planta.',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.add': 'Agregar',
    'activity.add.title': 'Agregar actividad',
    'activity.add.subtitle': 'para',
    'activity.add.typeLabel': 'Tipo de actividad *',
    'activity.add.periodLabel': 'Período *',
    'activity.add.from': 'Desde',
    'activity.add.to': 'Hasta',
    'activity.add.customLabel': 'Etiqueta personalizada (opcional)',
    'activity.edit.title': 'Editar actividad',
    'activity.edit.nameLabel': 'Etiqueta',
    'activity.edit.periodLabel': 'Período *',
    'activity.edit.deleteTitle': 'Eliminar actividad',
    'activity.edit.deleteMessage': '¿Realmente eliminar esta actividad?',
    'activity.edit.rangeError': 'El mes de inicio no puede ser posterior al mes de fin.',
    'activity.edit.namePlaceholder': 'p.ej. Sembrar',
    'activity.type.sow': 'Sembrar',
    'activity.type.plant': 'Plantar',
    'activity.type.fertilize': 'Fertilizar',
    'activity.type.water': 'Regar',
    'activity.type.prune': 'Podar',
    'activity.type.harvest': 'Cosechar',
    'activity.type.protect': 'Protección invernal',
    'activity.type.mulch': 'Acolchar',
  },
  it: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendario delle piante',
    'calendar.addPlant': 'Nuova pianta',
    'calendar.months.short': [
      'Gen',
      'Feb',
      'Mar',
      'Apr',
      'Mag',
      'Giu',
      'Lug',
      'Ago',
      'Set',
      'Ott',
      'Nov',
      'Dic',
    ],
    'agenda.previous': 'Precedente',
    'agenda.current': 'Attuale',
    'agenda.next': 'Prossimo',
    'agenda.noActivities': 'Nessuna attività',
    'agenda.months': [
      'Gen 1-15',
      'Gen 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'Mag 1-15',
      'Mag 16-31',
      'Giu 1-15',
      'Giu 16-30',
      'Lug 1-15',
      'Lug 16-31',
      'Ago 1-15',
      'Ago 16-31',
      'Set 1-15',
      'Set 16-30',
      'Ott 1-15',
      'Ott 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dic 1-15',
      'Dic 16-31',
    ],
    'settings.settings': 'Impostazioni',
    'settings.appearance': 'ASPETTO',
    'settings.dark': 'Scuro',
    'settings.system': 'Sistema',
    'settings.languageSection': 'LINGUA',
    'settings.exportSection': 'ESPORTA',
    'settings.exportData': 'Esporta come JSON',
    'settings.about2': 'INFORMAZIONI',
    'settings.versionLabel': 'Versione',
    'settings.exportSuccess': 'Esportazione riuscita!',
    'settings.successTitle': 'Successo',
    'settings.feedbackLink': 'Invia feedback',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gestisci le piante',
    'plants.add': '➕ Aggiungi nuova pianta',
    'plants.empty': 'Nessuna pianta ancora',
    'plants.activities': 'Attività',
    'plants.deleteTitle': 'Elimina pianta',
    'plants.deleteMessage': 'eliminare davvero?',
    'plants.deleteConfirm': 'Elimina',
    'plants.deleteCancel': 'Annulla',
    'plants.editTitle': 'Modifica pianta',
    'plants.editSave': 'Salva',
    'plants.fieldName': 'Nome della pianta',
    'plants.fieldNotes': 'Note',
    'plants.fieldLocation': 'Posizione',
    'plants.fieldCategory': 'Categoria',
    'plants.addTitle': 'Aggiungi nuova pianta',
    'plants.fieldNamePlaceholder': 'es. Pomodori',
    'plants.fieldNotesPlaceholder': 'es. Ortaggio popolare per balcone',
    'plants.addHint': "Dopo l'aggiunta, puoi creare attività per la pianta.",
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.add': 'Aggiungi',
    'activity.add.title': 'Aggiungi attività',
    'activity.add.subtitle': 'per',
    'activity.add.typeLabel': 'Tipo di attività *',
    'activity.add.periodLabel': 'Periodo *',
    'activity.add.from': 'Da',
    'activity.add.to': 'A',
    'activity.add.customLabel': 'Etichetta personalizzata (opzionale)',
    'activity.edit.title': 'Modifica attività',
    'activity.edit.nameLabel': 'Etichetta',
    'activity.edit.periodLabel': 'Periodo *',
    'activity.edit.deleteTitle': 'Elimina attività',
    'activity.edit.deleteMessage': 'Eliminare davvero questa attività?',
    'activity.edit.rangeError': 'Il mese di inizio non può essere dopo il mese di fine.',
    'activity.edit.namePlaceholder': 'es. Seminare',
    'activity.type.sow': 'Seminare',
    'activity.type.plant': 'Piantare',
    'activity.type.fertilize': 'Fertilizzare',
    'activity.type.water': 'Innaffiare',
    'activity.type.prune': 'Potare',
    'activity.type.harvest': 'Raccogliere',
    'activity.type.protect': 'Protezione invernale',
    'activity.type.mulch': 'Pacciamatura',
  },
  pl: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Kalendarz roślin',
    'calendar.addPlant': 'Nowa roślina',
    'calendar.months.short': [
      'Sty',
      'Lut',
      'Mar',
      'Kwi',
      'Maj',
      'Cze',
      'Lip',
      'Sie',
      'Wrz',
      'Paź',
      'Lis',
      'Gru',
    ],
    'agenda.previous': 'Poprzedni',
    'agenda.current': 'Bieżący',
    'agenda.next': 'Następny',
    'agenda.noActivities': 'Brak aktywności',
    'agenda.months': [
      'Sty 1-15',
      'Sty 16-31',
      'Lut 1-15',
      'Lut 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Kwi 1-15',
      'Kwi 16-30',
      'Maj 1-15',
      'Maj 16-31',
      'Cze 1-15',
      'Cze 16-30',
      'Lip 1-15',
      'Lip 16-31',
      'Sie 1-15',
      'Sie 16-31',
      'Wrz 1-15',
      'Wrz 16-30',
      'Paź 1-15',
      'Paź 16-31',
      'Lis 1-15',
      'Lis 16-30',
      'Gru 1-15',
      'Gru 16-31',
    ],
    'settings.settings': 'Ustawienia',
    'settings.appearance': 'WYGLĄD',
    'settings.dark': 'Ciemny',
    'settings.system': 'System',
    'settings.languageSection': 'JĘZYK',
    'settings.exportSection': 'EKSPORT',
    'settings.exportData': 'Eksportuj jako JSON',
    'settings.about2': 'O APLIKACJI',
    'settings.versionLabel': 'Wersja',
    'settings.exportSuccess': 'Eksport zakończony sukcesem!',
    'settings.successTitle': 'Sukces',
    'settings.feedbackLink': 'Wyślij opinię',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Zarządzaj roślinami',
    'plants.add': '➕ Dodaj nową roślinę',
    'plants.empty': 'Brak roślin',
    'plants.activities': 'Aktywności',
    'plants.deleteTitle': 'Usuń roślinę',
    'plants.deleteMessage': 'na pewno usunąć?',
    'plants.deleteConfirm': 'Usuń',
    'plants.deleteCancel': 'Anuluj',
    'plants.editTitle': 'Edytuj roślinę',
    'plants.editSave': 'Zapisz',
    'plants.fieldName': 'Nazwa rośliny',
    'plants.fieldNotes': 'Notatki',
    'plants.fieldLocation': 'Lokalizacja',
    'plants.fieldCategory': 'Kategoria',
    'plants.addTitle': 'Dodaj nową roślinę',
    'plants.fieldNamePlaceholder': 'np. Pomidory',
    'plants.fieldNotesPlaceholder': 'np. Popularne warzywo na balkon',
    'plants.addHint': 'Po dodaniu możesz tworzyć aktywności dla rośliny.',
    'common.cancel': 'Anuluj',
    'common.save': 'Zapisz',
    'common.add': 'Dodaj',
    'activity.add.title': 'Dodaj aktywność',
    'activity.add.subtitle': 'dla',
    'activity.add.typeLabel': 'Typ aktywności *',
    'activity.add.periodLabel': 'Okres *',
    'activity.add.from': 'Od',
    'activity.add.to': 'Do',
    'activity.add.customLabel': 'Własna etykieta (opcjonalnie)',
    'activity.edit.title': 'Edytuj aktywność',
    'activity.edit.nameLabel': 'Etykieta',
    'activity.edit.periodLabel': 'Okres *',
    'activity.edit.deleteTitle': 'Usuń aktywność',
    'activity.edit.deleteMessage': 'Na pewno usunąć tę aktywność?',
    'activity.edit.rangeError': 'Miesiąc startowy nie może być późniejszy niż miesiąc końcowy.',
    'activity.edit.namePlaceholder': 'np. Siać',
    'activity.type.sow': 'Siać',
    'activity.type.plant': 'Sadzić',
    'activity.type.fertilize': 'Nawozić',
    'activity.type.water': 'Podlewać',
    'activity.type.prune': 'Przycinać',
    'activity.type.harvest': 'Zbierać',
    'activity.type.protect': 'Ochrona zimowa',
    'activity.type.mulch': 'Ściółkować',
  },
  nl: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Plantenkalender',
    'calendar.addPlant': 'Nieuwe plant',
    'calendar.months.short': [
      'Jan',
      'Feb',
      'Mrt',
      'Apr',
      'Mei',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Okt',
      'Nov',
      'Dec',
    ],
    'agenda.previous': 'Vorige',
    'agenda.current': 'Huidig',
    'agenda.next': 'Volgend',
    'agenda.noActivities': 'Geen activiteiten',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Feb 1-15',
      'Feb 16-28',
      'Mrt 1-15',
      'Mrt 16-31',
      'Apr 1-15',
      'Apr 16-30',
      'Mei 1-15',
      'Mei 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Aug 1-15',
      'Aug 16-31',
      'Sep 1-15',
      'Sep 16-30',
      'Okt 1-15',
      'Okt 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dec 1-15',
      'Dec 16-31',
    ],
    'settings.settings': 'Instellingen',
    'settings.appearance': 'UITERLIJK',
    'settings.dark': 'Donker',
    'settings.system': 'Systeem',
    'settings.languageSection': 'TAAL',
    'settings.exportSection': 'EXPORTEREN',
    'settings.exportData': 'Exporteren als JSON',
    'settings.about2': 'OVER',
    'settings.versionLabel': 'Versie',
    'settings.exportSuccess': 'Export geslaagd!',
    'settings.successTitle': 'Gelukt',
    'settings.feedbackLink': 'Feedback sturen',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Planten beheren',
    'plants.add': '➕ Nieuwe plant toevoegen',
    'plants.empty': 'Nog geen planten',
    'plants.activities': 'Activiteiten',
    'plants.deleteTitle': 'Plant verwijderen',
    'plants.deleteMessage': 'echt verwijderen?',
    'plants.deleteConfirm': 'Verwijderen',
    'plants.deleteCancel': 'Annuleren',
    'plants.editTitle': 'Plant bewerken',
    'plants.editSave': 'Opslaan',
    'plants.fieldName': 'Plantnaam',
    'plants.fieldNotes': 'Notities',
    'plants.fieldLocation': 'Locatie',
    'plants.fieldCategory': 'Categorie',
    'plants.addTitle': 'Nieuwe plant toevoegen',
    'plants.fieldNamePlaceholder': 'bijv. Tomaten',
    'plants.fieldNotesPlaceholder': 'bijv. Populaire groente voor balkon',
    'plants.addHint': 'Na het toevoegen kun je activiteiten aanmaken voor de plant.',
    'common.cancel': 'Annuleren',
    'common.save': 'Opslaan',
    'common.add': 'Toevoegen',
    'activity.add.title': 'Activiteit toevoegen',
    'activity.add.subtitle': 'voor',
    'activity.add.typeLabel': 'Activiteitstype *',
    'activity.add.periodLabel': 'Periode *',
    'activity.add.from': 'Van',
    'activity.add.to': 'Tot',
    'activity.add.customLabel': 'Aangepast label (optioneel)',
    'activity.edit.title': 'Activiteit bewerken',
    'activity.edit.nameLabel': 'Label',
    'activity.edit.periodLabel': 'Periode *',
    'activity.edit.deleteTitle': 'Activiteit verwijderen',
    'activity.edit.deleteMessage': 'Activiteit echt verwijderen?',
    'activity.edit.rangeError': 'Startmaand mag niet na eindmaand liggen.',
    'activity.edit.namePlaceholder': 'bijv. Zaaien',
    'activity.type.sow': 'Zaaien',
    'activity.type.plant': 'Planten',
    'activity.type.fertilize': 'Bemesten',
    'activity.type.water': 'Gieten',
    'activity.type.prune': 'Snoeien',
    'activity.type.harvest': 'Oogsten',
    'activity.type.protect': 'Winterbescherming',
    'activity.type.mulch': 'Mulchen',
  },
  pt: {
    'nav.calendar': '📅',
    'nav.agenda': '📋',
    'calendar.title': 'Calendário de plantas',
    'calendar.addPlant': 'Nova planta',
    'calendar.months.short': [
      'Jan',
      'Fev',
      'Mar',
      'Abr',
      'Mai',
      'Jun',
      'Jul',
      'Ago',
      'Set',
      'Out',
      'Nov',
      'Dez',
    ],
    'agenda.previous': 'Anterior',
    'agenda.current': 'Atual',
    'agenda.next': 'Próximo',
    'agenda.noActivities': 'Sem atividades',
    'agenda.months': [
      'Jan 1-15',
      'Jan 16-31',
      'Fev 1-15',
      'Fev 16-28',
      'Mar 1-15',
      'Mar 16-31',
      'Abr 1-15',
      'Abr 16-30',
      'Mai 1-15',
      'Mai 16-31',
      'Jun 1-15',
      'Jun 16-30',
      'Jul 1-15',
      'Jul 16-31',
      'Ago 1-15',
      'Ago 16-31',
      'Set 1-15',
      'Set 16-30',
      'Out 1-15',
      'Out 16-31',
      'Nov 1-15',
      'Nov 16-30',
      'Dez 1-15',
      'Dez 16-31',
    ],
    'settings.settings': 'Configurações',
    'settings.appearance': 'APARÊNCIA',
    'settings.dark': 'Escuro',
    'settings.system': 'Sistema',
    'settings.languageSection': 'IDIOMA',
    'settings.exportSection': 'EXPORTAR',
    'settings.exportData': 'Exportar como JSON',
    'settings.about2': 'SOBRE',
    'settings.versionLabel': 'Versão',
    'settings.exportSuccess': 'Exportação bem-sucedida!',
    'settings.successTitle': 'Sucesso',
    'settings.feedbackLink': 'Enviar feedback',
    'settings.supportLink': 'Ko-fi',
    'plants.title': 'Gerir plantas',
    'plants.add': '➕ Adicionar nova planta',
    'plants.empty': 'Ainda sem plantas',
    'plants.activities': 'Atividades',
    'plants.deleteTitle': 'Eliminar planta',
    'plants.deleteMessage': 'eliminar mesmo?',
    'plants.deleteConfirm': 'Eliminar',
    'plants.deleteCancel': 'Cancelar',
    'plants.editTitle': 'Editar planta',
    'plants.editSave': 'Guardar',
    'plants.fieldName': 'Nome da planta',
    'plants.fieldNotes': 'Notas',
    'plants.fieldLocation': 'Localização',
    'plants.fieldCategory': 'Categoria',
    'plants.addTitle': 'Adicionar nova planta',
    'plants.fieldNamePlaceholder': 'ex. Tomates',
    'plants.fieldNotesPlaceholder': 'ex. Vegetal popular para varanda',
    'plants.addHint': 'Depois de adicionar, pode criar atividades para a planta.',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.add': 'Adicionar',
    'activity.add.title': 'Adicionar atividade',
    'activity.add.subtitle': 'para',
    'activity.add.typeLabel': 'Tipo de atividade *',
    'activity.add.periodLabel': 'Período *',
    'activity.add.from': 'De',
    'activity.add.to': 'Até',
    'activity.add.customLabel': 'Rótulo personalizado (opcional)',
    'activity.edit.title': 'Editar atividade',
    'activity.edit.nameLabel': 'Rótulo',
    'activity.edit.periodLabel': 'Período *',
    'activity.edit.deleteTitle': 'Eliminar atividade',
    'activity.edit.deleteMessage': 'Eliminar mesmo esta atividade?',
    'activity.edit.rangeError': 'O mês de início não pode ser posterior ao mês de fim.',
    'activity.edit.namePlaceholder': 'ex. Semear',
    'activity.type.sow': 'Semear',
    'activity.type.plant': 'Plantar',
    'activity.type.fertilize': 'Fertilizar',
    'activity.type.water': 'Regar',
    'activity.type.prune': 'Podar',
    'activity.type.harvest': 'Colher',
    'activity.type.protect': 'Proteção invernal',
    'activity.type.mulch': 'Mulchar',
  },
};

function detectSystemLanguage(): Language {
  try {
    let locale: string | undefined;
    if (Platform.OS === 'web') {
      // platform-safe: navigator only available in web context
      locale = typeof navigator !== 'undefined' ? navigator.language : undefined;
    }
    if (!locale) return 'de';
    const code = locale.split('-')[0].toLowerCase() as Language;
    return FULLY_LOCALIZED.includes(code) ? code : 'de';
  } catch {
    return 'de';
  }
}

const STORAGE_KEY = 'language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('de');
  const isUserSetRef = React.useRef(false);

  const setLanguage = async (lang: Language) => {
    isUserSetRef.current = true;
    setLanguageState(lang);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, lang);
    } catch (error) {
      console.error('Failed to save language:', error);
    }
  };

  const t = (key: string): TranslationValue | string => {
    return translations[language][key] || key;
  };

  // Load language from storage on mount; skip if user already chose a language
  React.useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((storedLang) => {
      if (isUserSetRef.current) return;
      if (storedLang && FULLY_LOCALIZED.includes(storedLang as Language)) {
        setLanguageState(storedLang as Language);
      } else {
        setLanguageState(detectSystemLanguage());
      }
    });
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
